fortune/fortune/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('userprofile.urls', namespace='users')),
]

fortune/userprofile/urls.py
from django.conf.urls import url

from .views import UserListView, UserCreateView, UserUpdateView, UserDetailView, UserDeleteView
from .views import export_xls


urlpatterns = [
	url(r'^$', UserListView.as_view(), name='list'),
	url(r'^create/$', UserCreateView.as_view(), name='create'),
	url(r'^update/(?P<pk>\d+)/$', UserUpdateView.as_view(), name='update'),
	url(r'^detail/(?P<pk>\d+)/$', UserDetailView.as_view(), name='detail'),
	url(r'^delete/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='delete'),
	url(r'^export/xls/$', export_xls, name='export_xls'),
]

fortune/userprofile/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    """
    UserProfile model extends User model for birthdate and random number
    """
    user = models.OneToOneField(User, related_name="profile")

    birth_date = models.DateField()

    # random number should be range(1, 100)
    random_number = models.PositiveSmallIntegerField(default=1)

    def get_eligible(self):
        # custom function to check if user is older than 13 years or not
        today = datetime.date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        if age < 13:
            return "Blocked"
        return "Allowed"

    def get_bizzfuzz(self):
        # get value from bizzfuzz algorithm
        if self.random_number % 3 == 0 and self.random_number % 5 == 0:
            return "BizzFuzz"
        elif self.random_number % 3 == 0:
            return "Bizz"
        elif self.random_number % 5 == 0:
            return "Fuzz"
        else:
            return self.random_number

fortune/userprofile/forms.py
import datetime

from django import forms
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import UserProfile


class UserForm(forms.ModelForm):
	"""
	Customised user profile form
	"""
	username = forms.CharField()
	birth_date = forms.DateField()

	class Meta:
		model = UserProfile
		fields = ['username', 'birth_date']

	def __init__(self, *args, **kwargs):
		super(UserForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper(self)
		self.helper.form_class = 'form-horizontal'
		self.helper.label_class = 'col-md-4'
		self.helper.field_class = 'col-md-4'
		self.helper.add_input(Submit('submit', 'Submit'))

	def clean_username(self):
		# check if new username is same as old one (for update of instance)
		if self.cleaned_data['username'] == self.initial.get('username', None):
			return self.cleaned_data['username']

		# check if username is used or not
		try:
			existing_user = User.objects.get(username=self.cleaned_data['username'])
			raise forms.ValidationError("Username is already used!")
		except User.DoesNotExist:
			pass
		return self.cleaned_data['username']

	def clean_birth_date(self):
		# check if birth_date is larger than today
		birth_dt = self.cleaned_data['birth_date']
		if birth_dt > datetime.date.today():
			raise forms.ValidationError("Birth date can't be great than today")
		return birth_dt

fortune/userprofile/views.py
import random
import xlwt

from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse_lazy

from .models import UserProfile
from .forms import UserForm


class UserListView(ListView):
    """
    View to list all users
    """
    model = UserProfile
    template_name = "users/list.html"


class UserCreateView(CreateView):
    """
    View to create a user
    We define a custom form with username and birthdate field
    """
    model = UserProfile
    form_class = UserForm
    template_name = 'users/create.html'

    def get_success_url(self):
        return reverse_lazy('users:list')

    def form_valid(self, form):
        # create user object first
        username = form.cleaned_data['username']
        user = User.objects.create_user(username)

        # generate random variable
        rand_val = random.randint(1, 100)

        # generate user profile
        profile = UserProfile(user=user, birth_date=form.cleaned_data['birth_date'], random_number=rand_val)
        profile.save()

        return HttpResponseRedirect(self.get_success_url())


class UserUpdateView(UpdateView):
    """
    View to modify a user
    """
    model = UserProfile
    form_class = UserForm
    template_name = 'users/update.html'

    def get_success_url(self):
        return reverse_lazy('users:list')

    def form_valid(self, form):
        # update username
        self.object.user.username = form.cleaned_data['username']
        # update birth_date
        self.object.birth_date = form.cleaned_data['birth_date']
        self.object.user.save()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_initial(self):
        init_value = super(UserUpdateView, self).get_initial()
        init_value['username'] = self.object.user.username
        return init_value


class UserDetailView(DetailView):
    """
    View to show detailed info of User
    """
    model = UserProfile
    template_name = 'users/detail.html'


class UserDeleteView(DeleteView):
    """
    View to delete user
    """
    model = UserProfile
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users:list')


def export_xls(request):
    """
    generate excel file for user list
    """
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="users.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Users')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Username', 'Birthday', 'Eligible', 'Random Number', 'BizzFuzz',]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    for profile in UserProfile.objects.all():
        row_num += 1
        ws.write(row_num, 0, profile.user.username)
        ws.write(row_num, 1, profile.birth_date.strftime('%Y-%m-%d'))
        ws.write(row_num, 2, profile.get_eligible())
        ws.write(row_num, 3, profile.random_number)
        ws.write(row_num, 4, profile.get_bizzfuzz())

    wb.save(response)
    return response

fortune/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="page-header">
            <h1>Philip's Python & Django Test</h1>
        </div>
        {% block content %}
        {% endblock %}
    </div>  
</body>
</html>

fortune/templates/users/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}User Create{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<form method="POST" action="." class="form-horizontal" role="form">
			{% crispy form %}
		</form>
	</div>
	<div class="col-md-12">
		<a href="{% url 'users:list' %}" class="btn btn-default">Go to User List</a>
	</div>
</div>
{% endblock %}

fortune/templates/users/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}User Delete{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<form method="POST" action=".">
			{% csrf_token %}
			<p>Are you sure to delete user - {{ object.user.username }}</p>
			<button type="submit" class="btn btn-danger">Confirm</button>
			<a href="{% url 'users:list' %}" class="btn btn-default">Go to User List</a>
		</form>
	</div>
</div>
{% endblock %}

fortune/templates/users/detail.html
{% extends 'base.html' %}

{% block title %}User Detail{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<table class="table table-bordered">
			<tbody>
				<tr>
					<td>Username</td>
					<td>{{ object.user.username }}</td>
				</tr>
				<tr>
					<td>Birthday</td>
					<td>{{ object.birth_date }}</td>
				</tr>
				<tr>
					<td>Random Number</td>
					<td>{{ object.random_number }}</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="col-md-12">
		<a href="{% url 'users:list' %}" class="btn btn-default">Back to User List</a>
	</div>
</div>
{% endblock %}

fortune/templates/users/list.html
{% extends 'base.html' %}
{% load custom_tag %}

{% block title %}User List{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Username</th>
					<th>Birthday</th>
					<th>Eligible</th>
					<th>Random Number</th>
					<th>BizzFuzz</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for object in object_list %}
				<tr>
					<td><a href="{% url 'users:detail' pk=object.pk %}">{{ object.user.username }}</a></td>
					<td>{{ object.birth_date }}</td>
					<td>{% get_eligible object %}</td>
					<td>{{ object.random_number }}</td>
					<td>{% get_bizzfuzz object %}</td>
					<td>
						<a href="{% url 'users:update' pk=object.pk %}" class="btn-xs btn-success">Edit</a>
						<a href="{% url 'users:delete' pk=object.pk %}" class="btn-xs btn-danger">Delete</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col-md-12">
		<a href="{% url 'users:create' %}" class="btn btn-default">Create</a>
		<a href="{% url 'users:export_xls' %}" class="btn btn-success">Export XLS</a>
	</div>
</div>
{% endblock %}

fortune/templates/users/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}User Update{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<form method="POST" action="." class="form-horizontal" role="form">
			{% crispy form %}
		</form>
	</div>
	<div class="col-md-12">
		<a href="{% url 'users:list' %}" class="btn btn-default">Go to User List</a>
	</div>
</div>
{% endblock %}